### ISSUE TITLE
add 1 way direction feature

### ISSUE THREAD

**Issue by danielR2001** [yousifk/marquee_widget#1]
hi, I was wondering if you could add a new feature to your package - one-way direction: this feature is very simple its just removing the back animation and just jumping to start (kind of a full loop), the text would all disappear in one side and reappear on the other side (just like Spotify does in his marquee) #

**Comment by sunjianan9900** [comment]
+1

**Comment by yousifk** [comment]
Thanks for Suggest 
I did it

**Comment by Vingtoft** [comment]
@yousifk Awesome you implemented it! Can you please tell us how to enable one-way direction? Thanks!
