### ISSUE TITLE
dot "." at end go to front

### ISSUE THREAD

**Issue by kessero** [yousifk/marquee_widget#4]
I notice wired behawior.
If text is for example "test." In app i get ".test"
if text is ".test" in app is "test."
Some wired beahawior is with dot "."
Why is this happen and what can be done with it beside manualy change string?

This draft code corect behavior.
`String setDotInRightPlace(String t){
  String a;
  if(t.endsWith('. ')){
    a = t.substring(0, t.length-1);
    a = "."+a;
  }
  return a;
}`

**Comment by yousifk** [comment]
I check example at version 1.0.0, everything it's ok.
